export const FETCH_PROFILE = 'FETCH_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FETCH_TENANTS = 'FETCH_TENANTS';
export const UPDATE_TENANT = 'UPDATE_TENANT';
export const FETCH_ADMINS = 'FETCH_ADMINS';
export const FETCH_PAYMENTS = 'FETCH_PAYMENTS';
export const SEARCH_PAYMENT = 'SEARCH_PAYMENT';
export const SEARCH_TENANT = 'SEARCH_TENANT';
